// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated from ..\mus\instrumentos.asm
// Generated by wyztrackerparser v0.1 20200515

#asm
     
    ; Tabla de instrumentos 
    .TABLA_PAUTAS
        defw PAUTA_0,PAUTA_1,PAUTA_2,PAUTA_3,PAUTA_4,PAUTA_5,PAUTA_6 
     
    ; Tabla de efectos 
    .TABLA_SONIDOS
        defw SONIDO0,SONIDO1,SONIDO2,SONIDO3 
     
    ;Pautas (instrumentos) 
    ;Instrumento 'Bajo' 
    .PAUTA_0
        defb 46,0,12,0,10,0,9,0,129 
    ;Instrumento 'triririn' 
    .PAUTA_1
        defb 46,0,13,0,12,0,10,0,10,0,9,0,8,0,11,0,10,0,9,0,129 
    ;Instrumento 'chip1' 
    .PAUTA_2
        defb 7,0,8,0,9,0,9,0,8,0,7,0,6,0,129 
    ;Instrumento 'onda1' 
    .PAUTA_3
        defb 45,0,12,0,12,0,11,0,11,0,10,0,10,0,9,0,129 
    ;Instrumento 'Onda2' 
    .PAUTA_4
        defb 7,0,8,0,8,0,8,0,7,0,6,0,6,0,6,0,6,0,6,0,5,0,5,0,5,0,5,0,5,0,138 
    ;Instrumento 'Chip2' 
    .PAUTA_5
        defb 7,0,8,0,9,0,8,0,7,0,6,0,129 
    ;Instrumento 'Onda3' 
    .PAUTA_6
        defb 77,0,12,0,11,0,10,0,9,0,8,0,7,0,9,0,8,0,7,0,129 
     
    ;Efectos 
    ;Efecto 'bass drum' 
    .SONIDO0
        defb 23,63,0,116,110,0,255 
    ;Efecto 'drum' 
    .SONIDO1
        defb 162,47,0,23,93,9,255 
    ;Efecto 'hithat' 
    .SONIDO2
        defb 0,10,5,255 
    ;Efecto 'bass drum vol 2' 
    .SONIDO3
        defb 186,58,0,0,102,0,162,131,0,255 
     
    ;Frecuencias para las notas 
#endasm
