// CPC Palette with HW values
// Generated by mkts_om v0.5.20210614
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks [] = {
	0x14, // FF000000
	0x00, // FF808080
	0x0C, // FFFF0000
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B  // FFFFFFFF
};

