// CPC Palette with HW values
// Generated by mkts_om v0.5.20210614
// Copyleft 2017-2021 by The Mojon Twins

// custom salva

const unsigned char pal_1 [] = { // standard palette
	0x14, // FF000000	negro
	0x00, // FF808080	gris
	0x0C, // FFFF0000	rojo intenso
	0x0B, // FFFFFFFF	blanco
};

const unsigned char pal_2 [] = { // dark palette
	0x14, // FF000000	negro
	0x00, // FF808080	gris
	0x1C, // FF800000	rojo oscuro
	0x0B, // FFFFFFFF	blanco
};

const unsigned char pal_3 [] = { // warm palette
	0x14, // FF000000	negro
	0x00, // FF808080	gris
	0x0C, // FFFF0000	rojo intenso
	0x03, // FFFFFF80	amarillo claro
};

/*
	0x14, // FF000000	negro
	0x04, // FF000080	azul oscuro	
	0x15, // FF0000FF	azul intenso
	0x1C, // FF800000	rojo oscuro
	0x18, // FF800080	morado	
	0x1D, // FF8000FF	lila
	0x0C  // FFFF0000	rojo intenso
	0x05, // FFFF0080	magenta
	0x0D, // FFFF00FF	magenta claro
	0x16, // FF008000	verde oscuro
	0x06, // FF008080	celeste oscuro
	0x17, // FF0080FF	azul cielo	  
	0x1E, // FF808000	amarillo dorado
	0x00, // FF808080	gris
	0x1F, // FF8080FF	azul pastel
	0x0E, // FFFF8000	naranja
	0x07, // FFFF8080	rosa pastel
	0x0F, // FFFF80FF	rosa
	0x1A, // FF80FF00	verde claro
	0x02, // FF00FF80	verde mar
	0x13, // FF00FFFF	celeste claro
	0x1A, // FF80FF00	lima
	0x19, // FF80FF80	verde pastel
	0x1B, // FF80FFFF	celeste pastel
	0x0A, // FFFFFF00	amarillo intenso
	0x03, // FFFFFF80	amarillo claro
	0x0B, // FFFFFFFF	blanco

*/